all: add_test_cases manage_test_group make_group_by_content

add_test_cases: add_test_cases.hs
	ghc  -o add_test_cases add_test_cases.hs

manage_test_group: manage_test_group.hs
	ghc -o manage_test_group manage_test_group.hs

make_group_by_content: make_group_by_content.hs
	ghc -o make_group_by_content make_group_by_content.hs
