all: add_test_cases manage_test_group

add_test_cases: add_test_cases.hs
	ghc  -o add_test_cases add_test_cases.hs

manage_test_group: manage_test_group.hs
	ghc -o manage_test_group manage_test_group.hs
